/* Auto-generated by genmsg_cpp for file /home/atica/catkin_ws/src/Modulo_GPS/msg/msg_gps.msg */
#ifndef MODULO_GPS_MESSAGE_MSG_GPS_H
#define MODULO_GPS_MESSAGE_MSG_GPS_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace Modulo_GPS
{
template <class ContainerAllocator>
struct msg_gps_ {
  typedef msg_gps_<ContainerAllocator> Type;

  msg_gps_()
  : latitude(0.0)
  , longitude(0.0)
  , altitude(0.0)
  , roll(0.0)
  , pitch(0.0)
  , yaw(0.0)
  {
  }

  msg_gps_(const ContainerAllocator& _alloc)
  : latitude(0.0)
  , longitude(0.0)
  , altitude(0.0)
  , roll(0.0)
  , pitch(0.0)
  , yaw(0.0)
  {
  }

  typedef double _latitude_type;
  double latitude;

  typedef double _longitude_type;
  double longitude;

  typedef float _altitude_type;
  float altitude;

  typedef float _roll_type;
  float roll;

  typedef float _pitch_type;
  float pitch;

  typedef float _yaw_type;
  float yaw;


  typedef boost::shared_ptr< ::Modulo_GPS::msg_gps_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::Modulo_GPS::msg_gps_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct msg_gps
typedef  ::Modulo_GPS::msg_gps_<std::allocator<void> > msg_gps;

typedef boost::shared_ptr< ::Modulo_GPS::msg_gps> msg_gpsPtr;
typedef boost::shared_ptr< ::Modulo_GPS::msg_gps const> msg_gpsConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::Modulo_GPS::msg_gps_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::Modulo_GPS::msg_gps_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace Modulo_GPS

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::Modulo_GPS::msg_gps_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::Modulo_GPS::msg_gps_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::Modulo_GPS::msg_gps_<ContainerAllocator> > {
  static const char* value() 
  {
    return "f422e236d81ace5ed6f4a67c456a5ca3";
  }

  static const char* value(const  ::Modulo_GPS::msg_gps_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xf422e236d81ace5eULL;
  static const uint64_t static_value2 = 0xd6f4a67c456a5ca3ULL;
};

template<class ContainerAllocator>
struct DataType< ::Modulo_GPS::msg_gps_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Modulo_GPS/msg_gps";
  }

  static const char* value(const  ::Modulo_GPS::msg_gps_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::Modulo_GPS::msg_gps_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float64 latitude\n\
float64 longitude\n\
float32 altitude\n\
float32 roll \n\
float32 pitch\n\
float32 yaw\n\
";
  }

  static const char* value(const  ::Modulo_GPS::msg_gps_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::Modulo_GPS::msg_gps_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::Modulo_GPS::msg_gps_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.latitude);
    stream.next(m.longitude);
    stream.next(m.altitude);
    stream.next(m.roll);
    stream.next(m.pitch);
    stream.next(m.yaw);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct msg_gps_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::Modulo_GPS::msg_gps_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::Modulo_GPS::msg_gps_<ContainerAllocator> & v) 
  {
    s << indent << "latitude: ";
    Printer<double>::stream(s, indent + "  ", v.latitude);
    s << indent << "longitude: ";
    Printer<double>::stream(s, indent + "  ", v.longitude);
    s << indent << "altitude: ";
    Printer<float>::stream(s, indent + "  ", v.altitude);
    s << indent << "roll: ";
    Printer<float>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<float>::stream(s, indent + "  ", v.pitch);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
  }
};


} // namespace message_operations
} // namespace ros

#endif // MODULO_GPS_MESSAGE_MSG_GPS_H

