/* Auto-generated by genmsg_cpp for file /home/atica/catkin_ws/src/Navegacion_Atica/Modulo_Navegacion/msg/msg_gps.msg */
#ifndef MODULO_NAVEGACION_MESSAGE_MSG_GPS_H
#define MODULO_NAVEGACION_MESSAGE_MSG_GPS_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace Modulo_Navegacion
{
template <class ContainerAllocator>
struct msg_gps_ {
  typedef msg_gps_<ContainerAllocator> Type;

  msg_gps_()
  : latitude(0.0)
  , longitude(0.0)
  , height(0.0)
  , pitch(0.0)
  , yaw(0.0)
  , roll(0.0)
  , velocity_x(0.0)
  , velocity_y(0.0)
  , velocity_z(0.0)
  {
  }

  msg_gps_(const ContainerAllocator& _alloc)
  : latitude(0.0)
  , longitude(0.0)
  , height(0.0)
  , pitch(0.0)
  , yaw(0.0)
  , roll(0.0)
  , velocity_x(0.0)
  , velocity_y(0.0)
  , velocity_z(0.0)
  {
  }

  typedef float _latitude_type;
  float latitude;

  typedef float _longitude_type;
  float longitude;

  typedef float _height_type;
  float height;

  typedef float _pitch_type;
  float pitch;

  typedef float _yaw_type;
  float yaw;

  typedef float _roll_type;
  float roll;

  typedef float _velocity_x_type;
  float velocity_x;

  typedef float _velocity_y_type;
  float velocity_y;

  typedef float _velocity_z_type;
  float velocity_z;


  typedef boost::shared_ptr< ::Modulo_Navegacion::msg_gps_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::Modulo_Navegacion::msg_gps_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct msg_gps
typedef  ::Modulo_Navegacion::msg_gps_<std::allocator<void> > msg_gps;

typedef boost::shared_ptr< ::Modulo_Navegacion::msg_gps> msg_gpsPtr;
typedef boost::shared_ptr< ::Modulo_Navegacion::msg_gps const> msg_gpsConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::Modulo_Navegacion::msg_gps_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::Modulo_Navegacion::msg_gps_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace Modulo_Navegacion

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::Modulo_Navegacion::msg_gps_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::Modulo_Navegacion::msg_gps_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::Modulo_Navegacion::msg_gps_<ContainerAllocator> > {
  static const char* value() 
  {
    return "60954aed4adc07e00019828b664121f7";
  }

  static const char* value(const  ::Modulo_Navegacion::msg_gps_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x60954aed4adc07e0ULL;
  static const uint64_t static_value2 = 0x0019828b664121f7ULL;
};

template<class ContainerAllocator>
struct DataType< ::Modulo_Navegacion::msg_gps_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Modulo_Navegacion/msg_gps";
  }

  static const char* value(const  ::Modulo_Navegacion::msg_gps_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::Modulo_Navegacion::msg_gps_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float32 latitude\n\
float32 longitude\n\
float32 height\n\
float32 pitch\n\
float32 yaw\n\
float32 roll\n\
float32 velocity_x\n\
float32 velocity_y\n\
float32 velocity_z\n\
\n\
";
  }

  static const char* value(const  ::Modulo_Navegacion::msg_gps_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::Modulo_Navegacion::msg_gps_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::Modulo_Navegacion::msg_gps_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.latitude);
    stream.next(m.longitude);
    stream.next(m.height);
    stream.next(m.pitch);
    stream.next(m.yaw);
    stream.next(m.roll);
    stream.next(m.velocity_x);
    stream.next(m.velocity_y);
    stream.next(m.velocity_z);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct msg_gps_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::Modulo_Navegacion::msg_gps_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::Modulo_Navegacion::msg_gps_<ContainerAllocator> & v) 
  {
    s << indent << "latitude: ";
    Printer<float>::stream(s, indent + "  ", v.latitude);
    s << indent << "longitude: ";
    Printer<float>::stream(s, indent + "  ", v.longitude);
    s << indent << "height: ";
    Printer<float>::stream(s, indent + "  ", v.height);
    s << indent << "pitch: ";
    Printer<float>::stream(s, indent + "  ", v.pitch);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
    s << indent << "roll: ";
    Printer<float>::stream(s, indent + "  ", v.roll);
    s << indent << "velocity_x: ";
    Printer<float>::stream(s, indent + "  ", v.velocity_x);
    s << indent << "velocity_y: ";
    Printer<float>::stream(s, indent + "  ", v.velocity_y);
    s << indent << "velocity_z: ";
    Printer<float>::stream(s, indent + "  ", v.velocity_z);
  }
};


} // namespace message_operations
} // namespace ros

#endif // MODULO_NAVEGACION_MESSAGE_MSG_GPS_H

