(cl:in-package CITIUS_Control_PositionOrientation-msg)
(cl:export '(POSITIONSTATUS-VAL
          POSITIONSTATUS
          ORIENTATIONSTATUS-VAL
          ORIENTATIONSTATUS
          LATITUDE-VAL
          LATITUDE
          LONGITUDE-VAL
          LONGITUDE
          ALTITUDE-VAL
          ALTITUDE
          ROLL-VAL
          ROLL
          PITCH-VAL
          PITCH
          YAW-VAL
          YAW
          VELX-VAL
          VELX
          VELY-VAL
          VELY
          VELZ-VAL
          VELZ
          ACCX-VAL
          ACCX
          ACCY-VAL
          ACCY
          ACCZ-VAL
          ACCZ
          RATEX-VAL
          RATEX
          RATEY-VAL
          RATEY
          RATEZ-VAL
          RATEZ
))