(cl:defpackage CITIUS_Control_Manager-srv
  (:use )
  (:export
   "SRV_NODESTATUS"
   "<SRV_NODESTATUS-REQUEST>"
   "SRV_NODESTATUS-REQUEST"
   "<SRV_NODESTATUS-RESPONSE>"
   "SRV_NODESTATUS-RESPONSE"
   "SRV_VEHICLESTATUS"
   "<SRV_VEHICLESTATUS-REQUEST>"
   "SRV_VEHICLESTATUS-REQUEST"
   "<SRV_VEHICLESTATUS-RESPONSE>"
   "SRV_VEHICLESTATUS-RESPONSE"
  ))

