(cl:defpackage CITIUS_Control_Communication-srv
  (:use )
  (:export
   "SRV_DZOOM"
   "<SRV_DZOOM-REQUEST>"
   "SRV_DZOOM-REQUEST"
   "<SRV_DZOOM-RESPONSE>"
   "SRV_DZOOM-RESPONSE"
   "SRV_POLARITY"
   "<SRV_POLARITY-REQUEST>"
   "SRV_POLARITY-REQUEST"
   "<SRV_POLARITY-RESPONSE>"
   "SRV_POLARITY-RESPONSE"
   "SRV_VEHICLESTATUS"
   "<SRV_VEHICLESTATUS-REQUEST>"
   "SRV_VEHICLESTATUS-REQUEST"
   "<SRV_VEHICLESTATUS-RESPONSE>"
   "SRV_VEHICLESTATUS-RESPONSE"
  ))

