/* Auto-generated by genmsg_cpp for file /home/atica/catkin_ws/src/Common_files/msg/msg_fcn_aux.msg */
#ifndef COMMON_FILES_MESSAGE_MSG_FCN_AUX_H
#define COMMON_FILES_MESSAGE_MSG_FCN_AUX_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace Common_files
{
template <class ContainerAllocator>
struct msg_fcn_aux_ {
  typedef msg_fcn_aux_<ContainerAllocator> Type;

  msg_fcn_aux_()
  : type_msg(false)
  , function(0)
  , value(false)
  {
  }

  msg_fcn_aux_(const ContainerAllocator& _alloc)
  : type_msg(false)
  , function(0)
  , value(false)
  {
  }

  typedef uint8_t _type_msg_type;
  uint8_t type_msg;

  typedef uint8_t _function_type;
  uint8_t function;

  typedef uint8_t _value_type;
  uint8_t value;


  typedef boost::shared_ptr< ::Common_files::msg_fcn_aux_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::Common_files::msg_fcn_aux_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct msg_fcn_aux
typedef  ::Common_files::msg_fcn_aux_<std::allocator<void> > msg_fcn_aux;

typedef boost::shared_ptr< ::Common_files::msg_fcn_aux> msg_fcn_auxPtr;
typedef boost::shared_ptr< ::Common_files::msg_fcn_aux const> msg_fcn_auxConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::Common_files::msg_fcn_aux_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::Common_files::msg_fcn_aux_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace Common_files

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::Common_files::msg_fcn_aux_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::Common_files::msg_fcn_aux_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::Common_files::msg_fcn_aux_<ContainerAllocator> > {
  static const char* value() 
  {
    return "5ac596cebd65fb2d60c3c460c58ab4a2";
  }

  static const char* value(const  ::Common_files::msg_fcn_aux_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x5ac596cebd65fb2dULL;
  static const uint64_t static_value2 = 0x60c3c460c58ab4a2ULL;
};

template<class ContainerAllocator>
struct DataType< ::Common_files::msg_fcn_aux_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Common_files/msg_fcn_aux";
  }

  static const char* value(const  ::Common_files::msg_fcn_aux_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::Common_files::msg_fcn_aux_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bool type_msg\n\
uint8 function\n\
bool value      \n\
\n\
";
  }

  static const char* value(const  ::Common_files::msg_fcn_aux_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::Common_files::msg_fcn_aux_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::Common_files::msg_fcn_aux_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.type_msg);
    stream.next(m.function);
    stream.next(m.value);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct msg_fcn_aux_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::Common_files::msg_fcn_aux_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::Common_files::msg_fcn_aux_<ContainerAllocator> & v) 
  {
    s << indent << "type_msg: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.type_msg);
    s << indent << "function: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.function);
    s << indent << "value: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.value);
  }
};


} // namespace message_operations
} // namespace ros

#endif // COMMON_FILES_MESSAGE_MSG_FCN_AUX_H

