/* Auto-generated by genmsg_cpp for file /home/atica/catkin_ws/src/Common_files/msg/msg_camera.msg */
#ifndef COMMON_FILES_MESSAGE_MSG_CAMERA_H
#define COMMON_FILES_MESSAGE_MSG_CAMERA_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace Common_files
{
template <class ContainerAllocator>
struct msg_camera_ {
  typedef msg_camera_<ContainerAllocator> Type;

  msg_camera_()
  : image()
  {
  }

  msg_camera_(const ContainerAllocator& _alloc)
  : image(_alloc)
  {
  }

  typedef std::vector<int8_t, typename ContainerAllocator::template rebind<int8_t>::other >  _image_type;
  std::vector<int8_t, typename ContainerAllocator::template rebind<int8_t>::other >  image;


  typedef boost::shared_ptr< ::Common_files::msg_camera_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::Common_files::msg_camera_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct msg_camera
typedef  ::Common_files::msg_camera_<std::allocator<void> > msg_camera;

typedef boost::shared_ptr< ::Common_files::msg_camera> msg_cameraPtr;
typedef boost::shared_ptr< ::Common_files::msg_camera const> msg_cameraConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::Common_files::msg_camera_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::Common_files::msg_camera_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace Common_files

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::Common_files::msg_camera_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::Common_files::msg_camera_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::Common_files::msg_camera_<ContainerAllocator> > {
  static const char* value() 
  {
    return "a7e4fad7b43f0e22a2b2fb0c9470f7d1";
  }

  static const char* value(const  ::Common_files::msg_camera_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xa7e4fad7b43f0e22ULL;
  static const uint64_t static_value2 = 0xa2b2fb0c9470f7d1ULL;
};

template<class ContainerAllocator>
struct DataType< ::Common_files::msg_camera_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Common_files/msg_camera";
  }

  static const char* value(const  ::Common_files::msg_camera_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::Common_files::msg_camera_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int8[] image\n\
";
  }

  static const char* value(const  ::Common_files::msg_camera_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::Common_files::msg_camera_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.image);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct msg_camera_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::Common_files::msg_camera_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::Common_files::msg_camera_<ContainerAllocator> & v) 
  {
    s << indent << "image[]" << std::endl;
    for (size_t i = 0; i < v.image.size(); ++i)
    {
      s << indent << "  image[" << i << "]: ";
      Printer<int8_t>::stream(s, indent + "  ", v.image[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // COMMON_FILES_MESSAGE_MSG_CAMERA_H

