/* Auto-generated by genmsg_cpp for file /home/atica/catkin_ws/src/Common_files/msg/msg_emergency_stop.msg */
#ifndef COMMON_FILES_MESSAGE_MSG_EMERGENCY_STOP_H
#define COMMON_FILES_MESSAGE_MSG_EMERGENCY_STOP_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace Common_files
{
template <class ContainerAllocator>
struct msg_emergency_stop_ {
  typedef msg_emergency_stop_<ContainerAllocator> Type;

  msg_emergency_stop_()
  : value(false)
  {
  }

  msg_emergency_stop_(const ContainerAllocator& _alloc)
  : value(false)
  {
  }

  typedef uint8_t _value_type;
  uint8_t value;


  typedef boost::shared_ptr< ::Common_files::msg_emergency_stop_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::Common_files::msg_emergency_stop_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct msg_emergency_stop
typedef  ::Common_files::msg_emergency_stop_<std::allocator<void> > msg_emergency_stop;

typedef boost::shared_ptr< ::Common_files::msg_emergency_stop> msg_emergency_stopPtr;
typedef boost::shared_ptr< ::Common_files::msg_emergency_stop const> msg_emergency_stopConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::Common_files::msg_emergency_stop_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::Common_files::msg_emergency_stop_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace Common_files

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::Common_files::msg_emergency_stop_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::Common_files::msg_emergency_stop_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::Common_files::msg_emergency_stop_<ContainerAllocator> > {
  static const char* value() 
  {
    return "e431d687bf4b2c65fbd94b12ae0cb5d9";
  }

  static const char* value(const  ::Common_files::msg_emergency_stop_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xe431d687bf4b2c65ULL;
  static const uint64_t static_value2 = 0xfbd94b12ae0cb5d9ULL;
};

template<class ContainerAllocator>
struct DataType< ::Common_files::msg_emergency_stop_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Common_files/msg_emergency_stop";
  }

  static const char* value(const  ::Common_files::msg_emergency_stop_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::Common_files::msg_emergency_stop_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bool value\n\
";
  }

  static const char* value(const  ::Common_files::msg_emergency_stop_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::Common_files::msg_emergency_stop_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::Common_files::msg_emergency_stop_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.value);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct msg_emergency_stop_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::Common_files::msg_emergency_stop_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::Common_files::msg_emergency_stop_<ContainerAllocator> & v) 
  {
    s << indent << "value: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.value);
  }
};


} // namespace message_operations
} // namespace ros

#endif // COMMON_FILES_MESSAGE_MSG_EMERGENCY_STOP_H

