(cl:defpackage CITIUS_Control_Communication-msg
  (:use )
  (:export
   "<MSG_POSORIINFO>"
   "MSG_POSORIINFO"
   "<MSG_COMMAND>"
   "MSG_COMMAND"
   "<MSG_VEHICLEINFO>"
   "MSG_VEHICLEINFO"
   "<MSG_REARCAMERAINFO>"
   "MSG_REARCAMERAINFO"
   "<MSG_CTRLFRONTCAMERA>"
   "MSG_CTRLFRONTCAMERA"
   "<MSG_ELECTRICINFO>"
   "MSG_ELECTRICINFO"
   "<MSG_CTRLREARCAMERA>"
   "MSG_CTRLREARCAMERA"
   "<MSG_FRONTCAMERAINFO>"
   "MSG_FRONTCAMERAINFO"
  ))

