# Desacelerar presion (comando=0, value=0)
# Acelerar presion (comando=0, value=1)
# Valvula  cisterna OFF (comando=1, value=0)
# Valvula  cisterna ON  (comando=1, value=1)
# Valvula  autollenado OFF (comando=2, value=0)
# Valvula  autollenado ON (comando=2, value=1)
# Valvula  monitor OFF (comando=3, value=0)
# Valvula  monitor ON (comando=3, value=1)
# Movimiento PAN izquierda (comando=4, value=0)
# Movimiento PAN derecha   (comando=4, value=1)
# Movimiento PAN Stop (comando=4, value=2)
# Movimiento TILT arriba (comando=5, value=1)
# Movimiento tilt abajo (comando=5, value=0)
# Movimiento Tilt Stop (comando=5,value=0)
# Tipo de chorro CHORRO (comando 6,value=0)
# Tipo de chorro NIEBLA (comando 6,value=1)

int8 comando
int8 value
