"""autogenerated by genpy from Modulo_Gest_Sistema/msg_available_mode.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class msg_available_mode(genpy.Message):
  _md5sum = "3d0fd04f4ced9660c43caab85d5c5253"
  _type = "Modulo_Gest_Sistema/msg_available_mode"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """bool[12] available_mode
"""
  __slots__ = ['available_mode']
  _slot_types = ['bool[12]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       available_mode

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(msg_available_mode, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.available_mode is None:
        self.available_mode = [False,False,False,False,False,False,False,False,False,False,False,False]
    else:
      self.available_mode = [False,False,False,False,False,False,False,False,False,False,False,False]

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_struct_12B.pack(*self.available_mode))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      start = end
      end += 12
      self.available_mode = _struct_12B.unpack(str[start:end])
      self.available_mode = map(bool, self.available_mode)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(self.available_mode.tostring())
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      start = end
      end += 12
      self.available_mode = numpy.frombuffer(str[start:end], dtype=numpy.bool, count=12)
      self.available_mode = map(bool, self.available_mode)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_12B = struct.Struct("<12B")
