/* Auto-generated by genmsg_cpp for file /home/atica/catkin_ws/src/CITIUS/CITIUS_Control_Communication/srv/srv_polarity.srv */
#ifndef CITIUS_CONTROL_COMMUNICATION_SERVICE_SRV_POLARITY_H
#define CITIUS_CONTROL_COMMUNICATION_SERVICE_SRV_POLARITY_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace CITIUS_Control_Communication
{
template <class ContainerAllocator>
struct srv_polarityRequest_ {
  typedef srv_polarityRequest_<ContainerAllocator> Type;

  srv_polarityRequest_()
  : newPolarity(false)
  {
  }

  srv_polarityRequest_(const ContainerAllocator& _alloc)
  : newPolarity(false)
  {
  }

  typedef uint8_t _newPolarity_type;
  uint8_t newPolarity;


  typedef boost::shared_ptr< ::CITIUS_Control_Communication::srv_polarityRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::CITIUS_Control_Communication::srv_polarityRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct srv_polarityRequest
typedef  ::CITIUS_Control_Communication::srv_polarityRequest_<std::allocator<void> > srv_polarityRequest;

typedef boost::shared_ptr< ::CITIUS_Control_Communication::srv_polarityRequest> srv_polarityRequestPtr;
typedef boost::shared_ptr< ::CITIUS_Control_Communication::srv_polarityRequest const> srv_polarityRequestConstPtr;



template <class ContainerAllocator>
struct srv_polarityResponse_ {
  typedef srv_polarityResponse_<ContainerAllocator> Type;

  srv_polarityResponse_()
  : ret(false)
  {
  }

  srv_polarityResponse_(const ContainerAllocator& _alloc)
  : ret(false)
  {
  }

  typedef uint8_t _ret_type;
  uint8_t ret;


  typedef boost::shared_ptr< ::CITIUS_Control_Communication::srv_polarityResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::CITIUS_Control_Communication::srv_polarityResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct srv_polarityResponse
typedef  ::CITIUS_Control_Communication::srv_polarityResponse_<std::allocator<void> > srv_polarityResponse;

typedef boost::shared_ptr< ::CITIUS_Control_Communication::srv_polarityResponse> srv_polarityResponsePtr;
typedef boost::shared_ptr< ::CITIUS_Control_Communication::srv_polarityResponse const> srv_polarityResponseConstPtr;


struct srv_polarity
{

typedef srv_polarityRequest Request;
typedef srv_polarityResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct srv_polarity
} // namespace CITIUS_Control_Communication

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::CITIUS_Control_Communication::srv_polarityRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::CITIUS_Control_Communication::srv_polarityRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::CITIUS_Control_Communication::srv_polarityRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "eb5cb3c1a75b0d1dc40d9025e983ad31";
  }

  static const char* value(const  ::CITIUS_Control_Communication::srv_polarityRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xeb5cb3c1a75b0d1dULL;
  static const uint64_t static_value2 = 0xc40d9025e983ad31ULL;
};

template<class ContainerAllocator>
struct DataType< ::CITIUS_Control_Communication::srv_polarityRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "CITIUS_Control_Communication/srv_polarityRequest";
  }

  static const char* value(const  ::CITIUS_Control_Communication::srv_polarityRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::CITIUS_Control_Communication::srv_polarityRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bool newPolarity\n\
\n\
";
  }

  static const char* value(const  ::CITIUS_Control_Communication::srv_polarityRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::CITIUS_Control_Communication::srv_polarityRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::CITIUS_Control_Communication::srv_polarityResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::CITIUS_Control_Communication::srv_polarityResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::CITIUS_Control_Communication::srv_polarityResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "e2cc9e9d8c464550830df49c160979ad";
  }

  static const char* value(const  ::CITIUS_Control_Communication::srv_polarityResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xe2cc9e9d8c464550ULL;
  static const uint64_t static_value2 = 0x830df49c160979adULL;
};

template<class ContainerAllocator>
struct DataType< ::CITIUS_Control_Communication::srv_polarityResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "CITIUS_Control_Communication/srv_polarityResponse";
  }

  static const char* value(const  ::CITIUS_Control_Communication::srv_polarityResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::CITIUS_Control_Communication::srv_polarityResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bool ret\n\
\n\
\n\
";
  }

  static const char* value(const  ::CITIUS_Control_Communication::srv_polarityResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::CITIUS_Control_Communication::srv_polarityResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::CITIUS_Control_Communication::srv_polarityRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.newPolarity);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct srv_polarityRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::CITIUS_Control_Communication::srv_polarityResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.ret);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct srv_polarityResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<CITIUS_Control_Communication::srv_polarity> {
  static const char* value() 
  {
    return "2bb9a206470d2b7ae5b9c973e2da3934";
  }

  static const char* value(const CITIUS_Control_Communication::srv_polarity&) { return value(); } 
};

template<>
struct DataType<CITIUS_Control_Communication::srv_polarity> {
  static const char* value() 
  {
    return "CITIUS_Control_Communication/srv_polarity";
  }

  static const char* value(const CITIUS_Control_Communication::srv_polarity&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<CITIUS_Control_Communication::srv_polarityRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "2bb9a206470d2b7ae5b9c973e2da3934";
  }

  static const char* value(const CITIUS_Control_Communication::srv_polarityRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<CITIUS_Control_Communication::srv_polarityRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "CITIUS_Control_Communication/srv_polarity";
  }

  static const char* value(const CITIUS_Control_Communication::srv_polarityRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<CITIUS_Control_Communication::srv_polarityResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "2bb9a206470d2b7ae5b9c973e2da3934";
  }

  static const char* value(const CITIUS_Control_Communication::srv_polarityResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<CITIUS_Control_Communication::srv_polarityResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "CITIUS_Control_Communication/srv_polarity";
  }

  static const char* value(const CITIUS_Control_Communication::srv_polarityResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // CITIUS_CONTROL_COMMUNICATION_SERVICE_SRV_POLARITY_H

