(cl:in-package Modulo_Conduccion-msg)
(cl:export '(SENAL-VAL
          SENAL
          OPCION_ETC1-VAL
          OPCION_ETC1
          REVOLUCIONES_ETC1-VAL
          REVOLUCIONES_ETC1
          PORCENTAJE_ETC1-VAL
          PORCENTAJE_ETC1
          REVOLUCIONES2_ETC1-VAL
          REVOLUCIONES2_ETC1
          REVOLUCIONES_EEC1-VAL
          REVOLUCIONES_EEC1
          PORCENTAJE_EEC1-VAL
          PORCENTAJE_EEC1
          MARCHA-VAL
          MARCHA
          MARCHA_2-VAL
          MARCHA_2
          MARCHA_3-VAL
          MARCHA_3
          OPCION_EBC1-VAL
          OPCION_EBC1
          PORCENTAJE_EBC1-VAL
          PORCENTAJE_EBC1
          OPCION_CCVS-VAL
          OPCION_CCVS
          KM_H_CCVS-VAL
          KM_H_CCVS
          OPCION2_CCVS-VAL
          OPCION2_CCVS
          OPCION3_CCVS-VAL
          OPCION3_CCVS
          OPCION4_CCVS-VAL
          OPCION4_CCVS
          PTO_STATE_CCVS-VAL
          PTO_STATE_CCVS
          OPCION_AUX-VAL
          OPCION_AUX
          OPCION2_AUX-VAL
          OPCION2_AUX
          OPCION3_AUX-VAL
          OPCION3_AUX
          OPCION_EEC2-VAL
          OPCION_EEC2
          OPCION2_EEC2-VAL
          OPCION2_EEC2
          PORCENTAJE_EEC2-VAL
          PORCENTAJE_EEC2
          PORCENTAJE2_EEC2-VAL
          PORCENTAJE2_EEC2
          GRADOS_ET-VAL
          GRADOS_ET
          GRADOS2_ET-VAL
          GRADOS2_ET
          GRADOS3_ET-VAL
          GRADOS3_ET
          BARES_EF-VAL
          BARES_EF
          BARES_SP-VAL
          BARES_SP
          BARES2_SP-VAL
          BARES2_SP
          BARES3_SP-VAL
          BARES3_SP
          BARES4_SP-VAL
          BARES4_SP
          BARES5_SP-VAL
          BARES5_SP
          BARES6_SP-VAL
          BARES6_SP
          BARES_AC-VAL
          BARES_AC
          GRADOS_AC-VAL
          GRADOS_AC
          KILOMETROS_VDHR-VAL
          KILOMETROS_VDHR
          AXLE-VAL
          AXLE
          KILOGRAMOS_VHEACS-VAL
          KILOGRAMOS_VHEACS
          HORAS-VAL
          HORAS
          DRIVERWORKING1-VAL
          DRIVERWORKING1
          DRIVERWORKING2-VAL
          DRIVERWORKING2
          OPCION_T-VAL
          OPCION_T
          DRIVERTIME1-VAL
          DRIVERTIME1
          OPCION2_T-VAL
          OPCION2_T
          OPCION3_T-VAL
          OPCION3_T
          DRIVERTIME2-VAL
          DRIVERTIME2
          OPCION4_T-VAL
          OPCION4_T
          OPCION5_T-VAL
          OPCION5_T
          OPCION6_T-VAL
          OPCION6_T
          OPCION7_T-VAL
          OPCION7_T
          KM_H_T-VAL
          KM_H_T
          PORCENTAJE_ERC-VAL
          PORCENTAJE_ERC
          OPCION_AUXSTAT-VAL
          OPCION_AUXSTAT
          OPCION2_AUXSTAT-VAL
          OPCION2_AUXSTAT
          LITROS-VAL
          LITROS
          KM_L-VAL
          KM_L
          OPCION_ETC3-VAL
          OPCION_ETC3
          OPCION2_ETC3-VAL
          OPCION2_ETC3
          PTO1STATE-VAL
          PTO1STATE
          PTO2STATE-VAL
          PTO2STATE
          NMVSTATE-VAL
          NMVSTATE
))