(cl:in-package CITIUS_Control_Driving-msg)
(cl:export '(STEERING-VAL
          STEERING
          THOTTLE-VAL
          THOTTLE
          BRAKE-VAL
          BRAKE
          PARKINGBRAKE-VAL
          PARKINGBRAKE
          GEAR-VAL
          GEAR
          SPEED-VAL
          SPEED
          MOTORRPM-VAL
          MOTORRPM
          MOTORTEMPERATURE-VAL
          MOTORTEMPERATURE
          LIGHTS-VAL
          LIGHTS
          BLINKERLEFT-VAL
          BLINKERLEFT
          BLINKERRIGHT-VAL
          BLINKERRIGHT
          DIPSS-VAL
          DIPSS
          DIPSR-VAL
          DIPSR
          DIPSP-VAL
          DIPSP
          KLAXON-VAL
          KLAXON
))