/* Auto-generated by genmsg_cpp for file /home/atica/catkin_ws/src/Modulo_Conduccion/msg/msg_com_teleop.msg */
#ifndef MODULO_CONDUCCION_MESSAGE_MSG_COM_TELEOP_H
#define MODULO_CONDUCCION_MESSAGE_MSG_COM_TELEOP_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace Modulo_Conduccion
{
template <class ContainerAllocator>
struct msg_com_teleop_ {
  typedef msg_com_teleop_<ContainerAllocator> Type;

  msg_com_teleop_()
  : id_element(0)
  , value(0)
  {
  }

  msg_com_teleop_(const ContainerAllocator& _alloc)
  : id_element(0)
  , value(0)
  {
  }

  typedef uint8_t _id_element_type;
  uint8_t id_element;

  typedef int16_t _value_type;
  int16_t value;


  typedef boost::shared_ptr< ::Modulo_Conduccion::msg_com_teleop_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::Modulo_Conduccion::msg_com_teleop_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct msg_com_teleop
typedef  ::Modulo_Conduccion::msg_com_teleop_<std::allocator<void> > msg_com_teleop;

typedef boost::shared_ptr< ::Modulo_Conduccion::msg_com_teleop> msg_com_teleopPtr;
typedef boost::shared_ptr< ::Modulo_Conduccion::msg_com_teleop const> msg_com_teleopConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::Modulo_Conduccion::msg_com_teleop_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::Modulo_Conduccion::msg_com_teleop_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace Modulo_Conduccion

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::Modulo_Conduccion::msg_com_teleop_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::Modulo_Conduccion::msg_com_teleop_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::Modulo_Conduccion::msg_com_teleop_<ContainerAllocator> > {
  static const char* value() 
  {
    return "8e68cf4eaf8cc2bf2ebbab2ba4940029";
  }

  static const char* value(const  ::Modulo_Conduccion::msg_com_teleop_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x8e68cf4eaf8cc2bfULL;
  static const uint64_t static_value2 = 0x2ebbab2ba4940029ULL;
};

template<class ContainerAllocator>
struct DataType< ::Modulo_Conduccion::msg_com_teleop_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Modulo_Conduccion/msg_com_teleop";
  }

  static const char* value(const  ::Modulo_Conduccion::msg_com_teleop_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::Modulo_Conduccion::msg_com_teleop_<ContainerAllocator> > {
  static const char* value() 
  {
    return "uint8 id_element\n\
int16 value\n\
";
  }

  static const char* value(const  ::Modulo_Conduccion::msg_com_teleop_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::Modulo_Conduccion::msg_com_teleop_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::Modulo_Conduccion::msg_com_teleop_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.id_element);
    stream.next(m.value);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct msg_com_teleop_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::Modulo_Conduccion::msg_com_teleop_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::Modulo_Conduccion::msg_com_teleop_<ContainerAllocator> & v) 
  {
    s << indent << "id_element: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id_element);
    s << indent << "value: ";
    Printer<int16_t>::stream(s, indent + "  ", v.value);
  }
};


} // namespace message_operations
} // namespace ros

#endif // MODULO_CONDUCCION_MESSAGE_MSG_COM_TELEOP_H

