/* Auto-generated by genmsg_cpp for file /home/atica/catkin_ws/src/Modulo_Gest_Sistema/msg/msg_mode.msg */
#ifndef MODULO_GEST_SISTEMA_MESSAGE_MSG_MODE_H
#define MODULO_GEST_SISTEMA_MESSAGE_MSG_MODE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace Modulo_Gest_Sistema
{
template <class ContainerAllocator>
struct msg_mode_ {
  typedef msg_mode_<ContainerAllocator> Type;

  msg_mode_()
  : mode(0)
  , status(0)
  {
  }

  msg_mode_(const ContainerAllocator& _alloc)
  : mode(0)
  , status(0)
  {
  }

  typedef uint8_t _mode_type;
  uint8_t mode;

  typedef uint8_t _status_type;
  uint8_t status;


  typedef boost::shared_ptr< ::Modulo_Gest_Sistema::msg_mode_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::Modulo_Gest_Sistema::msg_mode_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct msg_mode
typedef  ::Modulo_Gest_Sistema::msg_mode_<std::allocator<void> > msg_mode;

typedef boost::shared_ptr< ::Modulo_Gest_Sistema::msg_mode> msg_modePtr;
typedef boost::shared_ptr< ::Modulo_Gest_Sistema::msg_mode const> msg_modeConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::Modulo_Gest_Sistema::msg_mode_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::Modulo_Gest_Sistema::msg_mode_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace Modulo_Gest_Sistema

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::Modulo_Gest_Sistema::msg_mode_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::Modulo_Gest_Sistema::msg_mode_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::Modulo_Gest_Sistema::msg_mode_<ContainerAllocator> > {
  static const char* value() 
  {
    return "31202a93cf12686e4f3edec877644512";
  }

  static const char* value(const  ::Modulo_Gest_Sistema::msg_mode_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x31202a93cf12686eULL;
  static const uint64_t static_value2 = 0x4f3edec877644512ULL;
};

template<class ContainerAllocator>
struct DataType< ::Modulo_Gest_Sistema::msg_mode_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Modulo_Gest_Sistema/msg_mode";
  }

  static const char* value(const  ::Modulo_Gest_Sistema::msg_mode_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::Modulo_Gest_Sistema::msg_mode_<ContainerAllocator> > {
  static const char* value() 
  {
    return "uint8 mode\n\
uint8 status\n\
\n\
";
  }

  static const char* value(const  ::Modulo_Gest_Sistema::msg_mode_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::Modulo_Gest_Sistema::msg_mode_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::Modulo_Gest_Sistema::msg_mode_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.mode);
    stream.next(m.status);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct msg_mode_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::Modulo_Gest_Sistema::msg_mode_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::Modulo_Gest_Sistema::msg_mode_<ContainerAllocator> & v) 
  {
    s << indent << "mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mode);
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
  }
};


} // namespace message_operations
} // namespace ros

#endif // MODULO_GEST_SISTEMA_MESSAGE_MSG_MODE_H

