/* Auto-generated by genmsg_cpp for file /home/atica/catkin_ws/src/CITIUS/CITIUS_Control_FrontCamera/msg/msg_ctrlFrontCamera.msg */
#ifndef CITIUS_CONTROL_FRONTCAMERA_MESSAGE_MSG_CTRLFRONTCAMERA_H
#define CITIUS_CONTROL_FRONTCAMERA_MESSAGE_MSG_CTRLFRONTCAMERA_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace CITIUS_Control_FrontCamera
{
template <class ContainerAllocator>
struct msg_ctrlFrontCamera_ {
  typedef msg_ctrlFrontCamera_<ContainerAllocator> Type;

  msg_ctrlFrontCamera_()
  : isZoom(false)
  , isPan(false)
  , isTilt(false)
  , zoom(0.0)
  , pan(0.0)
  , tilt(0.0)
  {
  }

  msg_ctrlFrontCamera_(const ContainerAllocator& _alloc)
  : isZoom(false)
  , isPan(false)
  , isTilt(false)
  , zoom(0.0)
  , pan(0.0)
  , tilt(0.0)
  {
  }

  typedef uint8_t _isZoom_type;
  uint8_t isZoom;

  typedef uint8_t _isPan_type;
  uint8_t isPan;

  typedef uint8_t _isTilt_type;
  uint8_t isTilt;

  typedef float _zoom_type;
  float zoom;

  typedef float _pan_type;
  float pan;

  typedef float _tilt_type;
  float tilt;


  typedef boost::shared_ptr< ::CITIUS_Control_FrontCamera::msg_ctrlFrontCamera_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::CITIUS_Control_FrontCamera::msg_ctrlFrontCamera_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct msg_ctrlFrontCamera
typedef  ::CITIUS_Control_FrontCamera::msg_ctrlFrontCamera_<std::allocator<void> > msg_ctrlFrontCamera;

typedef boost::shared_ptr< ::CITIUS_Control_FrontCamera::msg_ctrlFrontCamera> msg_ctrlFrontCameraPtr;
typedef boost::shared_ptr< ::CITIUS_Control_FrontCamera::msg_ctrlFrontCamera const> msg_ctrlFrontCameraConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::CITIUS_Control_FrontCamera::msg_ctrlFrontCamera_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::CITIUS_Control_FrontCamera::msg_ctrlFrontCamera_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace CITIUS_Control_FrontCamera

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::CITIUS_Control_FrontCamera::msg_ctrlFrontCamera_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::CITIUS_Control_FrontCamera::msg_ctrlFrontCamera_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::CITIUS_Control_FrontCamera::msg_ctrlFrontCamera_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ff23505ed4df1f3d3844a0151a537e6b";
  }

  static const char* value(const  ::CITIUS_Control_FrontCamera::msg_ctrlFrontCamera_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xff23505ed4df1f3dULL;
  static const uint64_t static_value2 = 0x3844a0151a537e6bULL;
};

template<class ContainerAllocator>
struct DataType< ::CITIUS_Control_FrontCamera::msg_ctrlFrontCamera_<ContainerAllocator> > {
  static const char* value() 
  {
    return "CITIUS_Control_FrontCamera/msg_ctrlFrontCamera";
  }

  static const char* value(const  ::CITIUS_Control_FrontCamera::msg_ctrlFrontCamera_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::CITIUS_Control_FrontCamera::msg_ctrlFrontCamera_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bool isZoom\n\
bool isPan\n\
bool isTilt\n\
float32 zoom\n\
float32 pan\n\
float32 tilt\n\
";
  }

  static const char* value(const  ::CITIUS_Control_FrontCamera::msg_ctrlFrontCamera_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::CITIUS_Control_FrontCamera::msg_ctrlFrontCamera_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::CITIUS_Control_FrontCamera::msg_ctrlFrontCamera_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.isZoom);
    stream.next(m.isPan);
    stream.next(m.isTilt);
    stream.next(m.zoom);
    stream.next(m.pan);
    stream.next(m.tilt);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct msg_ctrlFrontCamera_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::CITIUS_Control_FrontCamera::msg_ctrlFrontCamera_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::CITIUS_Control_FrontCamera::msg_ctrlFrontCamera_<ContainerAllocator> & v) 
  {
    s << indent << "isZoom: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isZoom);
    s << indent << "isPan: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isPan);
    s << indent << "isTilt: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isTilt);
    s << indent << "zoom: ";
    Printer<float>::stream(s, indent + "  ", v.zoom);
    s << indent << "pan: ";
    Printer<float>::stream(s, indent + "  ", v.pan);
    s << indent << "tilt: ";
    Printer<float>::stream(s, indent + "  ", v.tilt);
  }
};


} // namespace message_operations
} // namespace ros

#endif // CITIUS_CONTROL_FRONTCAMERA_MESSAGE_MSG_CTRLFRONTCAMERA_H

